//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyecto()
        {
            this.Detalle_Pedido = new HashSet<Detalle_Pedido>();
        }
    
        public int id { get; set; }
        public int id_Alumno { get; set; }
        public int id_Tallerista_Categoria_Precio_Sesion { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public string Fecha_Final { get; set; }
        public Nullable<decimal> Precio_Proyecto { get; set; }
        public Nullable<int> Numero_sesiones { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Pedido> Detalle_Pedido { get; set; }
        public virtual Tallerista_Categoria_Precio_Sesion Tallerista_Categoria_Precio_Sesion { get; set; }
    }
}
